version: 2
jobs:
  build:
    docker:
      - image: node:12.19.0-alpine3.12
    working_directory: /usr/src
    steps:
      - add_ssh_keys
      - run:
          name: install-git-ssh
          command: apk update && apk add git openssh
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: unit-tests
          command: npm run test:unit
  release:
    machine: true
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name : patch-application
          command: |
            git config --global user.email "circleci@wealthwizards.com"
            git config --global user.name "Circle CI"
            npm version patch -m "Release %s [ci skip]"
      - deploy:
          name : deploy-git-changes
          command: git push --follow-tags
workflows:
  version: 2
  build_test_release:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
